name: 비트코인 데이터 조회

on:
  schedule:
    - cron: '*/3 * * * *'  # 매 3분마다 실행 (초, 분, 시간, 일, 월)
      # - cron: '0 */4 * * *'  # 매 4시간마다 실행
      # - cron: '0 0 */3 * *'  # 매 3일마다 0시에 실행
      # - cron: '0 0 * * 0'    # 매주 일요일 0시에 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean :build -x test
      - name: Run batch
        run: java -jar -Dspring.batch.job.names=tickerSlackJob ./build/libs/crypto-automatioon-0.0.1-SNAPSHOT.jar market=KRW-BTC